server:
  port: 8083

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.172.221:3306/bookstore?userUnicode=true&useSSL=false&characterEncoding=utf8
    password: kai2606110123
    username: root
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  global-config:
    db-column-underline: true
    field-strategy: 2
    refresh-mapper: true
    db-config:
      id-type: ASSIGN_ID
  typeAliasesPackage: com.gp.entity
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    check-config-location: false
  mapper-locations: classpath:mapper/*.xml
wxpay:
  enabled: false  # 暂时禁用微信支付配置
  app-id: wx1234567890abcdef
  mch-id: 1234567890
  private-key-path: src/main/resources/apiclient_key.pem
  merchant-serial-number: 5C5B1A7E0E1D2C3B4A59687786959483
  api-v3-key: ABCDEFGHIJKLMNOPQRSTUVWXYZ123456
  notify-url: https://your-test-domain.com/api/pay/notify
  refund-notify-url: https://your-test-domain.com/api/pay/refund/notify
gp:
  minio:
    endpointUrl: http://124.222.172.221:9000
    accessKey: 2AyrlhH3xJa8McdX4Gqh
    secreKey: BqXqVYiHt3std78ZJL76wA36cjduf3JiyHbuk2Pc
    bucketName: bookstore

